### PR TITLE
Fixed srg not found problem at setup task

### PR DESCRIPTION
**Pull request by FlowArg**

### CODE REVIEW

**Comment by Venji10** [comment]
I can confirm, that this fixes the error.

**Comment by joshturge** [comment]
When attempting to setup with this patch, I still get the same error along with another: `Caused by: java.lang.IllegalStateException: ProjectScopeServices has been closed.`. Setting up older versions (1.15) works fine.

**Comment by FlowArg** [comment]
Hum, this error isn't related with my fix... So I don't know. :(

**Comment by coltonk9043** [comment]
This fix saved me lots of time, thank you! :)

**Comment by lakhinsu** [comment]
> When attempting to setup with this patch, I still get the same error along with another: `Caused by: java.lang.IllegalStateException: ProjectScopeServices has been closed.`. Setting up older versions (1.15) works fine.

Yeah same for me :(

**Comment by Derplex** [comment]
Still doesn't fix it for me.........
And i ALSO get the java.lang.IllegalStateException

**Comment by lakhinsu** [comment]
> Still doesn't fix it for me.........
> And i ALSO get the java.lang.IllegalStateException

can you try by doing it this way : [my previous comment link](https://github.com/Hexeption/MCP-Reborn/pull/37#issuecomment-653153404)

**Comment by Derplex** [comment]
Wow, it worked! Thanks a lot!

> > Still doesn't fix it for me.........
> > And i ALSO get the java.lang.IllegalStateException
> 
> can you try by doing it this way : [my previous comment link](https://github.com/Hexeption/MCP-Reborn/pull/37#issuecomment-653153404)

**Comment by lakhinsu** [comment]
> Wow, it worked! Thanks a lot!
> 
> > > Still doesn't fix it for me.........
> > > And i ALSO get the java.lang.IllegalStateException
> > 
> > 
> > can you try by doing it this way : [my previous comment link](https://github.com/Hexeption/MCP-Reborn/pull/37#issuecomment-653153404)

Welcome :) I was stuck here too :)

**Comment by Kroseida** [comment]
> 
> 
> > When attempting to setup with this patch, I still get the same error along with another: `Caused by: java.lang.IllegalStateException: ProjectScopeServices has been closed.`. Setting up older versions (1.15) works fine.
> 
> Yeah same for me :(
> 
> Edit: Fixed for me. They way i was building it was wrong. We have to run setup task in mcp just like in the README file from gradle explorer. I was directly doing run project.

If you are doing this, invalide cache of InteliiJ

**Pull request merged**
