### PR TITLE
Add Server support and Parameter Names

### PR DESCRIPTION
**Pull request by jacobo-mc**
This pull requuest adds a runserver task to build.gradle as well as support for parchment mappings, whitch also provides parameter names.

### CODE REVIEW

**Comment by novastosha** [comment]
Merge it, would be so useful

**Comment by pete-the-dev** [comment]
agree

**Comment by ghost** [comment]
please merge

**Comment by GavinGoGaming** [comment]
m e r g e e e eeee

**Comment by DenoneroDev** [comment]
Mergeeee the Parameter Names!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by vinc3nz** [comment]
The problem is, that if you try to do this for never versions, like 1.19, it does not work.

**Comment by josephworks** [comment]
The runserver task is kinda cool and I think @Hexeption should implement that.

On the other hand, MCP-Reborn uses official mappings, not community ones so I don't see this being merged.

**Comment by vinc3nz** [comment]
In parchment all classes, fields and methods stay like the official ones. The only thing that is being ADDED are parameter names (p_) and a bit of javadoc

**Comment by josephworks** [comment]
Sure, that may be convenient but it infringes on the idea of MCP. The original jar does not have those parameter names, and they are not provided by the official mappings, so you wouldn't be looking at a version of pure MCP source.

That being said, I think we could compromise by implementing this functionality but not making it enabled by default. it wouldn't be difficult to slap a car and if/else statements in the build.gradle.

@Hexeption please share your opinion on this.

**Comment by vinc3nz** [comment]
I will make a new pr for only the server support.

**Pull request closed without merging**
